// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado que est\xE1 conectado via MCP (id e e-mail).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const payload = { userId: ctx.getUserId(), email: ctx.getUserEmail() ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista clientes da conta do usu\xE1rio autenticado, opcionalmente filtrando por nome (busca parcial). Respeita o isolamento por tenant do Hora Pro.",
  inputSchema: {
    search: z.string().trim().min(1).max(120).optional().describe("Filtro por nome (opcional)."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("clients").select("id, full_name, phone, email, created_at").order("full_name", { ascending: true }).limit(limit ?? 25);
    if (search) q = q.ilike("full_name", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var DateSchema = z2.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use o formato YYYY-MM-DD");
var list_appointments_default = defineTool3({
  name: "list_appointments",
  title: "Listar agendamentos",
  description: "Lista agendamentos da conta do usu\xE1rio autenticado num intervalo de datas (YYYY-MM-DD). Se n\xE3o informar datas, retorna os do dia atual. Respeita o isolamento por tenant.",
  inputSchema: {
    from: DateSchema.optional().describe("Data inicial (YYYY-MM-DD). Padr\xE3o: hoje."),
    to: DateSchema.optional().describe("Data final (YYYY-MM-DD). Padr\xE3o: hoje."),
    limit: z2.number().int().min(1).max(200).optional().describe("M\xE1ximo de resultados (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const start = from ?? today;
    const end = to ?? start;
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("appointments").select(
      "id, appointment_date, start_time, end_time, status, notes, client_id, professional_id, service_id"
    ).gte("appointment_date", start).lte("appointment_date", end).order("appointment_date", { ascending: true }).order("start_time", { ascending: true }).limit(limit ?? 100);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { appointments: data ?? [], range: { from: start, to: end } }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nsgcllrbswodjoadybsj";
var mcp_default = defineMcp({
  name: "hora-pro-mcp",
  title: "Hora Pro",
  version: "0.1.0",
  instructions: "Ferramentas do Hora Pro (agenda para cl\xEDnicas de est\xE9tica). Use `whoami` para checar autentica\xE7\xE3o, `list_clients` para listar/buscar clientes e `list_appointments` para consultar agendamentos por data. Todas as ferramentas respeitam o isolamento por tenant (multi-cl\xEDnica) do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_clients_default, list_appointments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
